### ISSUE TITLE
Add D-CCA?

### ISSUE THREAD

**Issue by shu-hai** [mikelove/awesome-multi-omics#20]
Hello, would you please consider adding D-CCA on your list of "Multi-omics correlation or factor analysis"?
Link: https://github.com/shu-hai/D-CCA
Paper: https://doi.org/10.1080/01621459.2018.1543599

Thanks.

**Comment by mikelove** [comment]
Can you please make a pull request (PR):

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Here are our guidelines for contributing:

https://github.com/mikelove/awesome-multi-omics/blob/master/CONTRIBUTING.md

**Comment by shu-hai** [comment]
I just made the pull request. Could you help review it. Thanks.
