### ISSUE TITLE
MOGAMUN software

### ISSUE THREAD

**Issue by llrs** [mikelove/awesome-multi-omics#29]
Not sure it fits the repository conditions, as the software is not for multi-tables but multi-networks.

- 2020 - [MOGAMUN](https://bioconductor.org/packages/MOGAMUN/) A multi-objective genetic algorithm to find active modules in multiplex biological networks [preprint](https://www.biorxiv.org/content/10.1101/2020.05.25.114215v1)

**Comment by llrs** [comment]
If they are acceptable there are a couple more of entries that could be added:
- 2018 - [MolTi-DREAM](https://github.com/gilles-didier/MolTi-DREAM/) identifying communities from multiplex networks, and annotated the obtained clusters [article](https://dx.doi.org/10.12688%2Ff1000research.15486.2)
- 2019 - [RWR-MH](https://github.com/alberto-valdeolivas/RWR-MH) Random walk with restart on multiplex and heterogeneous biological networks [article](https://doi.org/10.1093/bioinformatics/bty637)

**Comment by mikelove** [comment]
Feel free to add a new section. I agree these are distinct from the factor-analysis-type methods, but under the umbrella of multi-omics certainly.

I have SNF listed under "clustering / classification / prediction", which also aggregates across networks.
