### ISSUE TITLE
Proposing new category: simulation of multi-omics datasets

### ISSUE THREAD

**Issue by llrs** [mikelove/awesome-multi-omics#42]
There are some tools that can be used to simulate multi-omics dataset. Maybe a new category could be added?

Here are a few I know:

- 2016 - [InterSIM](https://cran.r-project.org/package=InterSIM) - Chalise - methylation, gene expression and protein expression - [paper](https://dx.doi.org/10.1016%2Fj.cmpb.2016.02.011)
- 2019 - [MOSim](https://bioconductor.org/packages/MOSim) -  Martinez-Mira - RNA-seq, ATAC-seq (DNase-seq), ChIP-seq, small RNA-seq and Methyl-seq. - [preprint](http://dx.doi.org/10.1101/421834)
- 2019 - [OmicsSIMLA](https://omicssimla.sourceforge.io/) - Chung - - [paper](https://doi.org/10.1093/gigascience/giz045)

**Comment by mikelove** [comment]
Agree, feel free to add one!
